export const plugins = [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
    require('daisyui'),

];

module.exports = {
    darkMode: 'class',
    daisyui : {
        themes: [
            {
                mytheme: {
                    "primary": "#f4f1de",
                    "primary-content": "#141412",
                    "secondary": "#e07a5f",
                    "secondary-content": "#120503",
                    "accent": "#8783d1",
                    "accent-content": "#060610",
                    "neutral": "#472836",
                    "neutral-content": "#d8d0d3",
                    "base-100": "#fff",
                    "base-200": "#dedede",
                    "base-300": "#bebebe",
                    "base-content": "#161616",
                    "info": "#a5b4fc",
                    "info-content": "#0a0c16",
                    "success": "#bef264",
                    "success-content": "#0d1403",
                    "warning": "#fde047",
                    "warning-content": "#161202",
                    "error": "#e11d48",
                    "error-content": "#ffd8d9",
                },
            },
            'system',
            'light',
            'dark',
            'cupcake',
            'bumblebee',
            'emerald',
            'corporate',
            'synthwave',
            'retro',
            'cyberpunk',
            'valentine',
            'halloween',
            'garden',
            'forest',
            'aqua',
            'lofi',
            'pastel',
            'fantasy',
            'wireframe',
            'black',
            'luxury',
            'dracula',
            'cmyk',
            'autumn',
            'business',
            'acid',
            'lemonade',
            'night',
            'coffee',
            'winter',
        ],
    },
}